from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^login', views.login_view),
    url(r'^logout', views.logout_view),
    url(r'^camera', views.camera),
    url(r'^photo', views.photo),
    url(r'^api/mobile/get/count/light', views.api_mobile_get_count_light),
    url(r'^api/mobile/get/count/door', views.api_mobile_get_count_door),
    url(r'^api/mobile/get/setted_temperature', views.api_mobile_get_setted_temperature),
    url(r'^api/mobile/set/setted_temperature', views.api_mobile_set_setted_temperature),
    url(r'^api/mobile/get/door', views.api_mobile_get_door),
    url(r'^api/mobile/set/door', views.api_mobile_set_door),
    url(r'^api/mobile/get/light', views.api_mobile_get_light),
    url(r'^api/mobile/set/light', views.api_mobile_set_light),
    url(r'^api/mobile/get/spotlight', views.api_mobile_get_spotlight),
    url(r'^api/mobile/set/spotlight', views.api_mobile_set_spotlight),
    url(r'^api/set/randomtemperature', views.api_set_randomtemperature),
    url(r'^api/set/ip', views.api_set_ip),
    url(r'^api/get/temperature', views.api_get_temperature),
    url(r'^api/set/temperature', views.api_set_temperature),
    url(r'^api/get/setted_temperature', views.api_get_setted_temperature),
    url(r'^api/set/setted_temperature', views.api_set_setted_temperature),
    url(r'^api/get/door', views.api_get_door),
    url(r'^api/set/door', views.api_set_door),
    url(r'^api/get/light', views.api_get_light),
    url(r'^api/set/light', views.api_set_light),
    url(r'^api/get/spotlight', views.api_get_spotlight),
    url(r'^api/set/spotlight', views.api_set_spotlight),
    url(r'^log', views.showlog),
    url(r'^api/music/play', views.music_play),
    url(r'^api/music/stop', views.music_stop),
    url(r'^auth', views.auth),
    url(r'^chart_add', views.chart_add),
    url(r'^chart_update', views.chart_update),
    url(r'^chart', views.chart),
    url(r'^weather', views.get_weather),
    url(r'^', views.index),
]
